### ISSUE TITLE
Card image URL prefix is set twice

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-server#48]
If the config variable IMAGES_HOST is not set to none (empty string) then the report endpoint gives a broken image_url, e.g.

`"https://images.petabencana.id/https://images.petabencana.in/BJy4hENVZ.jpg"`

**Comment by matthewberryman** [comment]
I checked and this is something present in the database 
```
 31657 |   279 | 2017-07-02 23:46:14.202313+00 | 2017-07-02 23:45:03.011+00 | test                                                                                                         | grasp  | confirmed | flood         | en   | https://data.petabencana.id/cards/H1MHSbDVb | https://images.petabencana.id/https://images.petabencana.id/H1MHSbDVb.jpg
```

Currently exploring why this gets set twice

**Comment by matthewberryman** [comment]
It's because you had a bug in master branch of cognicity-schema https://github.com/urbanriskmap/cognicity-schema/blob/master/schema/reports/grasp/grasp.functions.sql#L9 - you used `||` which in postgresql is string concatenation. If you're happy for me to trash the dev database I can just rebuild from dev branch of cognicity-schema where this is now fixed, otherwise I will update just that function. Closing this as it's not a bug in cognicity-server and the issue with the schema is fixed in cognicity-schema dev branch.

**Comment by tomasholderness** [comment]
@matthewberryman - yes, please trash dev database and load new schema so we can test this. Thanks.
