### ISSUE TITLE
API Gateway cache does not take into account params

### ISSUE THREAD

**Issue by mgvarley** [urbanriskmap/cognicity-server#5]
The caching in API Gateway does not appear to take into account the query params.  So, for example:

https://data.petabencana.id/infrastructure/pumps?geoformat=geojson
https://data.petabencana.id/infrastructure/pumps?geoformat=topojson
https://data.petabencana.id/infrastructure/pumps

Do not behave as expected with API Gateway cache enabled.  The first call is cached and then subsequent geoformat requests are ignored.  I have toggled the cache off in API Gateway and enabled caching on the server and this behaves as expected.  Would be good to discuss and agree our strategy on caching, it may be that API Gateway cache is not fine grained enough for our requirements.

**Comment by matthewberryman** [comment]
The trouble is that the query parameters haven't been set up in API Gateway, so even in the absence of caching, things are breaking. I've now set up a city parameter for reports in the console:
![screenshot 2016-12-08 11 11 51](https://cloud.githubusercontent.com/assets/2288238/20993122/682773de-bd3c-11e6-81ff-9f6f55886e7e.png)
-the /reports/id route is handled by a different resource (proxy) path in API Gateway and I assume no from the code no need for a city there.
My apologies- I had been tracking the index.js files and not had time to delve into the model.js files for parameters.

I'll have a go at fixing it but there are some major inconsistencies between the code, API Gateway, https://github.com/urbanriskmap/petabencana-docs/ , and https://docs.petabencana.id , to list the ones I've found:
* In API gateway I don't have a v3 prefix but in the two (?) sets of documents there is a v3 listed.
* In API gateway and the code and the documentation examples the parameter is named "city" but in the rest of the documentation it's named "region". 
* In https://github.com/urbanriskmap/cognicity-server-v3/blob/master/src/api/routes/cards/model.js there's no city/region parameter but in the docs it lists a city/region and format parameter. I guess a result of copying and pasting in the docs.

If you want to avoid the API gateway you can hit the EB instance directly at https://api-server.petabencana.id/ and I wasn't seeing these sorts of issues there (no idea why @talltom said he was unless there was confusion around the URLs?)

I don't have access to the gitbook (unless that is generated from petabencana-docs in some way?) so I can't change that. @mgvarley 

cc @MaanasaPriyaa 

I'll try and update the API Gateway now (I have limited time today due to my wife's shifts) based on the code as the point of reference and assuming no v3 prefix for now.

**Comment by matthewberryman** [comment]
I can't see in model.js that reports takes a format, but if I test on api-server (to rule out the fact I haven't yet set it up in the API Gateway), I can see from testing that it will accept a format=json or format=xml, however it always returns json, in fact topojson; which reveals another possible API definition error is that in [config.js](https://github.com/urbanriskmap/cognicity-server-v3/blob/master/src/config.js) you've got a [FORMATS defined](https://github.com/urbanriskmap/cognicity-server-v3/blob/master/src/config.js#L26) as either json or xml, but I guess you want your formats back from the API to be strictly either topojson, geojson, or cap rather than the fact that they're either json or (for cap) xml.

**Comment by matthewberryman** [comment]
Unless I have things wrong. We really need to lock in the API and document it properly asap.

**Comment by matthewberryman** [comment]
Ok I think I have API Gateway up to speed with the code at least. I will double check and also play with caching (globally and individually per query parameter) tonight, having left off caching for now - but this should have resolved it for cached as well as the non-cached issue @talltom was seeing.

One other thing in the docs I've noticed is that we're missing feeds.

**Comment by tomasholderness** [comment]
@matthewberryman - re errors on EB instance; there was a bug in the reports SQL query which we fixed and pushed a few hours back. Suspect this was the cause of me seeing those errors. Will reply re. your other comments tomorrow.

**Comment by matthewberryman** [comment]
Ok. Everything was fine for me on api-server. 

I have just had time to go through the API Gateway settings. For cards[/id] and feeds/qlue I've not got any query parameters. For the rest I have format and city parameters for all the list ones and just format for the [/id] ones. I have 2 minutes of caching in API Gateway (with EB application-level cache off) for everything except for /floods and /reports. I will keep an eye on this.

**Comment by mgvarley** [comment]
Doing this today

Sent with Unibox

**Comment by mgvarley** [comment]
Again, not yet implemented. We are in development 

Sent with Unibox

**Comment by matthewberryman** [comment]
Even if stuff isn't implemented, I hope we can agree on the API spec so I can get it into API GW in preparation for implementation. Otherwise I'm just chasing the tail.

**Comment by matthewberryman** [comment]
Seems that AWS API Gateway doesn't respect individual cache settings (or I am misunderstanding what the tick boxes do - I will follow up tomorrow with docs). Anyway, turning of the global cache settings, but leaving the query parameters in place in API Gateway, is now producing correct results (aside from things needing to be defined/implemented).
