### ISSUE TITLE
Extended image support

### ISSUE THREAD

**Issue by tomasholderness** [urbanriskmap/cognicity-server#52]
1 request for large images available in client
Three folders:
- originals
- resized
- resized_large

2 should we support GIFs?
![cat](https://user-images.githubusercontent.com/944642/29733778-e211f80c-89bc-11e7-9301-2df92aee47f5.gif)

**Comment by talltom** [comment]
They see me rolling...

![cat](https://user-images.githubusercontent.com/944642/29733631-16398a42-89bc-11e7-9017-f208b478af85.gif)

**Comment by matthewberryman** [comment]
For other image sizes:
1. The schema needs to be updated to store perhaps just the base image filename rather than the full url, so then in petabencana.id we can reconstruct the full url dynamically on the fly depending on desktop / mobile (if I understand the intent here correctly). If you care about past events you would also need to modify the database.
2. Petabencana.id needs to be updated to select smaller / larger depending on desktop / mobile.
3. Ditto https://github.com/urbanriskmap/cognicity-recognition/issues/5 until https://github.com/urbanriskmap/cognicity-recognition/issues/4 is finished.
3. image-lambda processor [configuration](https://github.com/urbanriskmap/image-lambda/blob/master/config.json) needs to be updated along with [https://github.com/urbanriskmap/image-lambda/blob/master/serverless.yml](IAM policy)

For gif upload support:
1. We need to make sure that [cards accept and upload gif files](https://github.com/urbanriskmap/cognicity-cards/issues/9). 
Note that https://github.com/urbanriskmap/image-lambda supports non-animated gifs as inputs. I don't think we need to support animated gifs. Maybe down the track we should support proper video files?

**Comment by tomasholderness** [comment]
Update: 
- image_url is now set by the server
    - https://github.com/urbanriskmap/cognicity-server/blob/master/src/api/routes/cards/index.js#L246

**Comment by tomasholderness** [comment]
Closing this as back-end functionality complete. Outstanding UI tasks tracked in https://github.com/urbanriskmap/riskmap/issues/232
